[package]
name = "space-invaders"
version = "0.1.0"
authors = ["Deokhwan Kim"]
description = "space-invaders is an emulator for the Space Invaders arcade machine."
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
bitflags = "1.2.1"
i8080 = { git = "https://github.com/dkim/i8080.git", tag = "1.0.0", default_features = false }
luminance = "0.39.0"
luminance-derive = "0.5.3"
luminance-glfw = "0.12.1"
spin_sleep = "0.3.7"
structopt = { version = "0.3.11", features = ["wrap_help"] }
