[package]
name = "space-invaders"
version = "0.1.0"
authors = ["Deokhwan Kim"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
structopt = { version = "0.3.15", features = ["wrap_help"] }
