[package]
name = "space-invaders"
version = "0.1.0"
authors = ["Deokhwan Kim"]
description = "space-invaders is an emulator for the Space Invaders arcade machine."
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[badges]
github-actions = { repository = "dkim/space-invaders", workflow = "build" }

[dependencies]
bitflags = "1.2.1"
env_logger = "0.7.1"
i8080 = { git = "https://github.com/dkim/i8080.git", tag = "1.0.0", default_features = false }
log = "0.4.8"
luminance = "0.38.0"
luminance-derive = "0.5.2"
luminance-glfw = "0.12.0"
rodio = { version = "0.10.0", default-features = false, features = ["wav"] }
spin_sleep = "0.3.7"
structopt = { version = "0.3.8", features = ["wrap_help"] }
