[package]
name = "space-invaders"
version = "0.1.0"
authors = ["Deokhwan Kim"]
description = "space-invaders is an emulator for the Space Invaders arcade machine."
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
structopt = { version = "0.3.14", features = ["wrap_help"] }
