[licenses]
confidence-threshold = 1.0
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Zlib",
]

[bans]
multiple-versions = "deny"

[sources]
allow-git = [
  "https://github.com/dkim/i8080.git",
]
