[licenses]
confidence-threshold = 1.0
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "Zlib",
]

[bans]
multiple-versions = "deny"
skip = [
  { name = "winapi", version = "=0.2.8" }, # term_size 0.3.1
]

[sources]
allow-git = [
  "https://github.com/dkim/i8080.git",
]
