[licenses]
confidence-threshold = 1.0
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Zlib",
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "cfg-if", version = "0.1.10" },
]

[sources]
allow-git = [
  "https://github.com/dkim/i8080",
]
