[licenses]
confidence-threshold = 1.0
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "bitflags", version = "1.3.2" },
    { name = "jni", version = "0.19.0" },
    { name = "raw-window-handle", version = "0.4.3" },
    { name = "syn", version = "1.0.109" },
    { name = "windows-sys", version = "0.52.0" },
    { name = "windows-targets", version = "0.42.2" },
    { name = "windows-targets", version = "0.48.5" },
    { name = "windows_aarch64_gnullvm", version = "0.42.2" },
    { name = "windows_aarch64_gnullvm", version = "0.48.5" },
    { name = "windows_aarch64_msvc", version = "0.42.2" },
    { name = "windows_aarch64_msvc", version = "0.48.5" },
    { name = "windows_i686_gnu", version = "0.42.2" },
    { name = "windows_i686_gnu", version = "0.48.5" },
    { name = "windows_i686_msvc", version = "0.42.2" },
    { name = "windows_i686_msvc", version = "0.48.5" },
    { name = "windows_x86_64_gnu", version = "0.42.2" },
    { name = "windows_x86_64_gnu", version = "0.48.5" },
    { name = "windows_x86_64_gnullvm", version = "0.42.2" },
    { name = "windows_x86_64_gnullvm", version = "0.48.5" },
    { name = "windows_x86_64_msvc", version = "0.42.2" },
    { name = "windows_x86_64_msvc", version = "0.48.5" },
]

[sources]
allow-git = [
  "https://github.com/dkim/i8080",
]
