name: license

on:
  pull_request:
    branches:
      - '**'
    paths:
      - Cargo.toml
      - Cargo.lock
  push:
    branches-ignore:
    - staging.tmp
    - trying.tmp
    paths:
      - Cargo.toml
      - Cargo.lock
  schedule:
    - cron: '0 4 1 * *' # at 04:00 UTC on the first day of each month

jobs:
  cargo-deny:
    name: cargo deny
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install cargo-deny
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-deny
    - name: cargo deny
      uses: actions-rs/cargo@v1
      with:
        command: deny
        args: check
